services:
  tms-db:
    image: postgres:17-alpine
    container_name: tms-db
    restart: unless-stopped
    mem_limit: 2g      # Limita la RAM a 2 GB
    cpus: 2.0            # Limita el uso de CPU a 2 núcleos
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: America/Havana
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - tms-network
    security_opt:
      - no-new-privileges:true

  adminer:
    image: adminer:5.4.2
    container_name: tms-adminer
    restart: always
    # expose:
    #   - "8081"
    environment:
      - TZ=America/Havana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - tms-db
    networks:
      - tms-network
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tmsdb.rule=Host(`tmsdb.syscargo.cu`)"
      - "traefik.http.routers.tmsdb.entrypoints=websecure"
      - "traefik.http.routers.tmsdb.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tmsdb.middlewares=internal-strict@file"
#      - "traefik.http.routers.tmsdb.middlewares=auth@file,security-headers@file,gzip@file"
      - "traefik.http.services.tmsdb.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true

  backend:
    build:
      context: ./tms-backend
    container_name: tms-backend
    restart: always
    mem_limit: 2g      # Limita la RAM a 2 GB
    cpus: 2.0            # Limita el uso de CPU a 2 núcleos
    expose:
      - "5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      NODE_ENV: production
      TZ: America/Havana
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://127.0.0.1:5000/v1/origen/all"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      tms-db:
        condition: service_healthy
    networks:
      - tms-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-syscargo.rule=Host(`api.syscargo.cu`)"
      - "traefik.http.routers.api-syscargo.entrypoints=websecure"
      - "traefik.http.routers.api-syscargo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api-syscargo.middlewares=public-api@file"
      # Si NO manejas CORS en NestJS y el navegador llama directo a api.syscargo.cu,
      # usa esta línea en vez de la anterior:
      # - "traefik.http.routers.api-syscargo.middlewares=public-api@file,cors@file"
      - "traefik.http.services.api-syscargo.loadbalancer.server.port=5000"
#      - "traefik.http.routers.api-syscargo.middlewares=cors@file"
      - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true

  front-cliente:
    build:
      context: ./tms-front-cliente
    container_name: tms-front-cliente
    restart: always
    mem_limit: 512m      # Limita la RAM a 512 MB
    cpus: 0.5            # Limita el uso de CPU a 0.5 núcleos
    expose:
      - "80"
    environment:
      TZ: America/Havana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - backend
    networks:
      - tms-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syscargo.rule=Host(`tms.syscargo.cu`)"
      - "traefik.http.routers.syscargo.entrypoints=websecure"
      - "traefik.http.routers.syscargo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.syscargo.middlewares=public-web-tms@file"
      - "traefik.http.services.syscargo.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true

  front-admin:
    build:
      context: ./tms-front-admin
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: tms-front-admin
    restart: always
    mem_limit: 512m      # Limita la RAM a 512 MB
    cpus: 0.5            # Limita el uso de CPU a 0.5 núcleos
    expose:
      - "80"
    environment:
      TZ: America/Havana
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - backend
    networks:
      - tms-network
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admintms.rule=Host(`admin.syscargo.cu`)"
      - "traefik.http.routers.admintms.entrypoints=websecure"
      - "traefik.http.routers.admintms.tls.certresolver=letsencrypt"
      - "traefik.http.routers.admintms.middlewares=customer-portal-tms-admin@file"
      - "traefik.http.services.admintms.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    security_opt:
      - no-new-privileges:true

networks:
  tms-network:
    driver: bridge
  proxy:
    external: true